name: Build Little Fingers

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to create'
        default: '1.2'
        required: true
        type: string

env:
  LEVEL: ${{ inputs.version }}

jobs:   
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: xcodebuild
      run: |
        chmod +x xcodebuild.sh
        ./xcodebuild.sh
        cd build/Build/Products/release
        ditto -c -k --keepParent Little\ Fingers.app Little\ Fingers.zip
        

    - name: Create GitHub Draft
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.LEVEL }}
        name: Little Fingers v${{ env.LEVEL }}
        draft: true
        prerelease: false
        files: build/Build/Products/release/Little\ Fingers.zip